import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'insta_timeline/insta_timeline.widget.dart';

@RoutePage()
class MainTimelinePage extends ConsumerWidget {
  const MainTimelinePage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return InstaTimeline(appBar: null);
    // Immich can autogenerated Google Photos like memories but since we only upload a selection of photos, it
    // might be harder. On the other hand, maybe it can still be nice to have for users that uploads a lot
    // and does not create albums? Either way, leave it off until we have tested it so we don't turn it on
    // for old users without knowing how it behaves.
    // final hasMemories = ref.watch(driftMemoryFutureProvider.select((state) => state.value?.isNotEmpty ?? false));
    // return InstaTimeline(
    //   topSliverWidget: const SliverToBoxAdapter(child: DriftMemoryLane()),
    //   topSliverWidgetHeight: hasMemories ? 200 : 0,
    //   appBar: null,
    // );
  }
}
