
name: loomory
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.140.0+3010

environment:
  sdk: ^3.8.1

# Rely on transitive dependencies from immich_mobile for everything
dependencies:
  flutter:
    sdk: flutter
  immich_mobile:
    path: ./packages/immich/mobile
  auto_route: ^9.2.0
  background_downloader: ^9.2.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.3.3
  flutter_displaymode: ^0.6.0
  flutter_hooks: ^0.21.2
  easy_localization: ^3.0.7+1
  intl: ^0.20.0
  hooks_riverpod: ^2.6.1
  logging: ^1.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  path_provider_foundation: ^2.4.1
  package_info_plus: ^8.3.0
  permission_handler: ^11.4.0
  # Requires manual add in Podfile, see instructions on pub.dev
  # Otherwise we get Unable to find a specification for `share_handler_ios_models` depended upon by `share_handler_ios`
  # because of transitive dependency in packages/immich with no support in our Podfile for loomery
  share_handler: ^0.0.22  
  riverpod_annotation: ^2.6.1
  timezone: ^0.9.4
  worker_manager: ^7.2.3

# Check immich_mobile versions from time to time for dev_dependency versions
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.1
  riverpod_generator: ^2.6.1

# Review at some point, cast 2.1.0 from immich pulled in bonsoir 5.0.1 but when I build loomory it pulled in 5.1.11
dependency_overrides:
  bonsoir: 5.1.11


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/i18n/
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
